version: 2

sources:
  - name: staging  # Le nom de la source doit correspondre à celui utilisé dans vos modèles dbt.
    database: macro-topic-412617
    schema: ny_taxi  # Ce doit être le nom du schéma dans BigQuery où se trouvent vos tables.
    tables:
      - name: green_tripdata  # Nom de la table tel qu'il apparaît dans BigQuery.
      - name: yellow_tripdata  # Nom
    
